export const listings = [
  {
    id: "3312",
    name: "Sarthak Sambharia",
    exp: "3 years",
    job: "hr recruiter",
    location: "delhi",
    img: "./assets/1.jpg",
    contact: "sarthaksam@gmail.com",
  },
  {
    id: "8326",
    name: "Raj Yadav",
    exp: "1 years",
    job: "software engineer",
    location: "faridabad",
    img: "./assets/2.jpg",
    contact: "rajatyadav@gmail.com",
  },
  {
    id: "2112",
    name: "Bineet Sen",
    exp: "2 years",
    job: "project manager",
    location: "delhi",
    img: "./assets/5.jpg",
    contact: "bineetsen@gmail.com",
  },
  {
    id: "7221",
    name: "Gaura Tikku",
    exp: "4 years",
    job: "business analyst",
    location: "gurugram",
    img: "./assets/3.jpg",
    contact: "gauratikku@gmail.com",
  },
  {
    id: "3258",
    name: "Kavita Pokhariya",
    exp: "3 years",
    job: "data scientist",
    location: "Noida",
    img: "./assets/4.jpg",
    contact: "kavitapokher@gmail.com",
  },
];
